spring:
  application:
    name: metering-batch      # 어플리케이션 이름 = Github 레포지토리에서 관리하는 파일 애플리케이션 이름
  profiles:
    active: dev-common, dev-jdbc
  config:
    import: optional:configserver:http://localhost:8088 # import:optional:configserver사용 -> Spring cloud config server 주소
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080     # Spring Cloud Config Client 주소

# 클라이언트 코드에서 Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health, beans
    health:
      show-details: always

health:
  config:
    enabled: false
